<a href="https://colab.research.google.com/github/kripaa222/Kripa/blob/master/Worksheet0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import sys
# Check Python version
if sys.version_info.major == 3 and sys.version_info.minor >= 6:
  print("Hello, World!")
  print(f"Python version: {sys.version}")
else:
  print("Please use Python 3.6 or higher.")

Hello, World!
Python version: 3.11.11 (main, Dec  4 2024, 08:55:07) [GCC 11.4.0]


# **Data Types in Python**

*   **Mutable Data Types** : Mutable objects can be changed after they are created. This means you can modify their contents, such as adding or removing items, or changing their values without creating a new object. For example - list

*   **Immutable Data Types** : Immutable objects cannot be changed once they are created. Any operation that seems to modify an immutable object will actually create a new object instead of changing the original.For example - tuple

  Difference between Mutable and Immutable Data Types.

In [ ]:
# Mutable Data Type Example (List)
my_list = [1, 2, 3]
print("Original List:", my_list)

# Modifying the list (changing contents)
my_list.append(4)
print("Modified List:", my_list)

# Immutable Data Type Example (Tuple)
my_tuple = (1, 2, 3)
print("Original Tuple:", my_tuple)

# Trying to modify the tuple (will raise an error)
# my_tuple.append(4) # Uncommenting this line will raise an AttributeError

Original List: [1, 2, 3]
Modified List: [1, 2, 3, 4]
Original Tuple: (1, 2, 3)


# **Some Common Data Types in Python:**

**Data Type : Numeric (int, float, complex)**

In [ ]:
age = 23 #int
pi = 3.14 #float
temperature = -5.5 #float

print("data type of variable age = ", type(age))
print("data type of variable pi = ", type(pi))
print("data type of variable temperature = ", type(temperature))

data type of variable age =  <class 'int'>
data type of variable pi =  <class 'float'>
data type of variable temperature =  <class 'float'>


**Data Type : Sequence (String, List, Tuple)**

String

In [ ]:
name = "Alice"
greeting = "Hello"
address = "123 Main St"
print("data type of the variable name = ",type(name))
print("data type of the variable greeting = ",type(greeting))
print("data type of the variable address = ",type(address))

# slice only one element
print("The first letter of the name is:", name[0])
print("The last letter of the name is:", name[-1])

# slice a range of elements
print("The second letter to the fourth of the name is:", name[1:4])
print("The first two letters of the name are:", name[:2])
print("Substring starting from the third letter is:", name[2:])

data type of the variable name =  <class 'str'>
data type of the variable greeting =  <class 'str'>
data type of the variable address =  <class 'str'>
The first letter of the name is: A
The last letter of the name is: e
The second letter to the fourth of the name is: lic
The first two letters of the name are: Al
Substring starting from the third letter is: ice


List

In [ ]:
list1 = [1, 2, 3, 4]
mixed_list = [12, "Hello", True]
# List is mutable
mixed_list[0] = False
mixed_list

[False, 'Hello', True]

Tuple

In [ ]:
colors = ('red', 'green', 'yellow', 'blue')

print("First element:", colors[0])
print("Last two elements:", colors[2:])
print("Middle two elements:", colors[1:3])

#colors[0] = 'purple'
#colors # will generate an error as tuple is immutable, meaning their values cannot be changed once they are created.

First element: red
Last two elements: ('yellow', 'blue')
Middle two elements: ('green', 'yellow')


**Data Type : Mapping (Dict)**

In [ ]:
person = {'name':'John','age':30,'city':'Pittsburgh'}
print(f"Hello my name is {person['name']}. I am {person['age']} years old and I live at {person['city']}.")
print("All keys:", list(person.keys()))
print("All values:", list(person.values()))

Hello my name is John. I am 30 years old and I live at Pittsburgh.
All keys: ['name', 'age', 'city']
All values: ['John', 30, 'Pittsburgh']


**Data Type : Set (Set, Frozenset)**

In [ ]:
unique_numbers = {1,2,3,3,3,3,4,5}
print(unique_numbers)

{1, 2, 3, 4, 5}


**Data Type : Boolean**

In [ ]:
is_student = True
has_license = False
print("data type of the variable is_student = ",type(is_student))
print("data type of the variable has_license = ",type(has_license))

data type of the variable is_student =  <class 'bool'>
data type of the variable has_license =  <class 'bool'>


**Data Type : Special (Nonetype)**

In [ ]:
result = None
result

# **Logical Statements**



*   if
*   elif

*   else
*   Comparison operators

*   Logical Operators








**if-else statement**

In [ ]:
num = 10

if num > 0:
  print("Positive")
elif num == 0:
  print("Zero")
else:
  print("Non-positive")

Positive


**Comparison Operator**

*   ==: Equal to
*   !=: Not equal to

*   <: Less than
*   >: Greater than



*   <=: Less than or equal to
*   >=: Greater than or equal to







In [ ]:
x = 5
y = 10

if x > 0 and y < 20:
  print("Both conditions are true")

if x > 0 or y > 20:
  print("At least one condition is true")

if not x == 0:
  print("x is not equal to 0")

Both conditions are true
At least one condition is true
x is not equal to 0


**Logical Operators**


*   and

*   or
*   not




In [ ]:
# Define two boolean variables
a = True
b = False

# Using the ’and’ operator
if a and b:
  print("Both a and b are True")
else:
  print("Either a or b is False") # This will be printed

# Using the ’or’ operator
if a or b:
  print("At least one of a or b is True") # This will be printed
else:
  print("Both a and b are False")

# Using the ’not’ operator
if not a:
  print("a is False") # This will not be printed
else:
  print("a is True") # This will be printed

Either a or b is False
At least one of a or b is True
a is True


**Loops**



*   for loop

*   while loop
*   break


*   continue



In [ ]:
# for loop:
fruits = ["apple", "banana","cherry"]
for fruit in fruits:
  print(fruit)

# While loop:
count = 0
while count < 5:
  print("Count is:", count)
  count += 1

# Break
fruits = ["apple", "banana", "orange"]
print("loop 1")
for fruit in fruits:
  print(fruit)
  if fruit == "apple":
    break

# Continiue
print("loop 2")
for fruit in fruits:
  if fruit == "apple":
    continue
  else:
    print(fruit)

apple
banana
cherry
Count is: 0
Count is: 1
Count is: 2
Count is: 3
Count is: 4
loop 1
apple
loop 2
banana
orange


# **Functions**

Docstrings are important

In [ ]:
def add_binary(a, b):
  '''
  Returns the sum of two decimal numbers in binary digits.
  Parameters:
  a (int): A decimal integer
  b (int): Another decimal integer
  Returns:
  binary_sum (str): Binary string of the sum of a and b
  '''
  binary_sum = bin(a+b)[2:]
  return binary_sum

Built-in  Functions

In [ ]:
print("Hello, World!") # Output: Hello, World!
length = len("Hello") # Output: 5
data_type = type(42) # Output: <class ’int’>
total = sum([1, 2, 3]) # Output: 6

Hello, World!


Built-in methods

In [ ]:
# str.upper(): Converts all characters in a string to uppercase.
message = "hello".upper() # Output: "HELLO"
print(message)

# list.append(): Adds an element to the end of a list.
fruits = ["apple", "banana"]
fruits.append("cherry") # Output: ["apple", "banana", "cherry"]
print(fruits)

# dict.get(): Returns the value associated with a key in a dictionary.
info = {"name": "Alice", "age": 25}
age = info.get("age") # Output: 25
print(age)

HELLO
['apple', 'banana', 'cherry']
25


User-defined Function

In [ ]:
def temperature_converter():
  """
  Converts temperature between Celsius and Fahrenheit.
  This function prompts the user to specify the conversion type (Celsius to Fahrenheit or
  Fahrenheit to Celsius)
  and then asks for the temperature value. It calculates and returns the converted temperature.
  Returns:
  float: The converted temperature value.
  """
  print("Choose conversion type:")
  print("1. Celsius to Fahrenheit")
  print("2. Fahrenheit to Celsius")

  # Get conversion choice from user
  choice = input("Enter 1 or 2: ")

  if choice == "1":
    # Celsius to Fahrenheit conversion
    celsius = float(input("Enter temperature in Celsius: "))
    fahrenheit = (celsius * 9/5) + 32
    print(f"{celsius}C is equal to {fahrenheit}F")
    return fahrenheit

  elif choice == "2":
    # Fahrenheit to Celsius conversion
    fahrenheit = float(input("Enter temperature in Fahrenheit: "))
    celsius = (fahrenheit - 32) * 5/9
    print(f"{fahrenheit}F is equal to {celsius}C")
    return celsius

  else:
    print("Invalid choice. Please enter 1 or 2.")
    return None

# Call the function
temperature_converter()

Choose conversion type:
1. Celsius to Fahrenheit
2. Fahrenheit to Celsius
Enter 1 or 2: 1
Enter temperature in Celsius: 23
23.0C is equal to 73.4F


73.4

# **Global and Local Variables**

Global Variable

In [ ]:
x = 10 # Global Variable.

def print_global():
  print(x) # Accessing global variable

print_global() # Output: 10

10


Local Variable

In [ ]:
def print_local():
  y = 5 # Local variable
  print(y)

print_local() # Output: 5
print(y) # This would cause an error because y is not accessible outside the function

5
10


# **Exercises**

**Exercise on Functions:**

**Task 1**

Create a Python program that converts between different units of measurement.
• The program should:
  1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
  2. Ask the user to input the value to be converted.
  3. Perform the conversion and display the result.
  4. Handle potential errors, such as invalid input or unsupported conversion types.

• Requirements:
  1. Functions: Define at least one function to perform the conversion.
  2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).
  3. User Input: Prompt the user to select the conversion type and input the value.
  4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and
  return value.

• Conversion Options:
  1. Length:
  – Convert meters (m) to feet (ft).
  – Convert feet (ft) to meters (m).
  2. Weight:
  – Convert kilograms (kg) to pounds (lbs).
  – Convert pounds (lbs) to kilograms (kg).
  3. Volume:
  – Convert liters (L) to gallons (gal).
  – Convert gallons (gal) to liters (L).

In [1]:
def get_choice():
    """This function prompts the user to choose the type of conversion they want.
    Returns:
    str: The choice of conversion type.
    """

    conversion_options = {
        "1": ("m_to_ft", "Length: meters (m) to feet (ft)", "m", "ft"),
        "2": ("ft_to_m", "Length: feet (ft) to meters (m)", "ft", "m"),
        "3": ("kg_to_pounds", "Weight: kilograms (kg) to pounds (lbs)", "kg", "lbs"),
        "4": ("pounds_to_kg", "Weight: pounds (lbs) to kilograms (kg)", "lbs", "kg"),
        "5": ("L_to_gal", "Volume: liters (L) to gallons (gal)", "L", "gal"),
        "6": ("gal_to_L", "Volume: gallons (gal) to liters (L)", "gal", "L")
    }

    print("Select a conversion option:")
    for key, value in conversion_options.items():
        print(f"{key}. {value[1]}")

    choice = input("Enter the number of the conversion you want: ").strip()
    return conversion_options.get(choice, None)

def convert(value, conv_choice):
    """
    Converts the given value based on the conversion type.

    Parameters:
    conversion_functions (dict): A dictionary containing conversion functions.
    value (float): The value to be converted.
    conv_choice (str): The conversion type choice

    Returns:
    float: The converted value.
    """
    conversion_functions = {
        "m_to_ft": lambda v: v * 3.281,
        "ft_to_m": lambda v: v / 3.281,
        "kg_to_pounds": lambda v: v * 2.20462,
        "pounds_to_kg": lambda v: v * 0.453592,
        "L_to_gal": lambda v: v * 0.264172,
        "gal_to_L": lambda v: v * 3.78541
    }

    return conversion_functions.get(conv_choice, lambda v: None)(value)

def main():
    while True:
        conversion_choice = get_choice()

        if not conversion_choice:
            print("Invalid choice. Please select a valid option.")
            continue

        conv_type, desc, from_unit, to_unit = conversion_choice
        print(f"You have selected: {desc}")

        try:
            value = float(input(f"Enter the value in {from_unit}: "))
            converted_value = convert(value, conv_type)

            if converted_value is not None:
                print(f"{value} {from_unit} is equal to {converted_value:.4f} {to_unit}")
            else:
                print("Conversion error. Please try again.")

        except ValueError:
            print("Invalid input. Please enter a valid number.")

        another = input("Do you want to perform another conversion? (yes/no): ").strip().lower()
        if another != "yes":
            print("End of program!")
            break

if __name__ == "__main__":
    main()


Select a conversion option:
1. Length: meters (m) to feet (ft)
2. Length: feet (ft) to meters (m)
3. Weight: kilograms (kg) to pounds (lbs)
4. Weight: pounds (lbs) to kilograms (kg)
5. Volume: liters (L) to gallons (gal)
6. Volume: gallons (gal) to liters (L)
Enter the number of the conversion you want: 2
You have selected: Length: feet (ft) to meters (m)
Enter the value in ft: 4
4.0 ft is equal to 1.2191 m
Do you want to perform another conversion? (yes/no): no
End of program!


**Task - 2:**

Create a Python program that performs various mathematical operations on a list of numbers.
*   The program should:
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum of the numbers)
2. Ask the user to input a list of numbers (separated by spaces).
3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.
*   Requirements:
1. Functions: Define at least one function for each operation (sum, average, maximum, minimum).
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or empty lists).
3. User Input: Prompt the user to select the operation and input the list of numbers.
4. Docstrings: Include a docstring in each function to describe its purpose, parameters, and
return value.

In [2]:
def find_sum(nums):
    """
    Calculates the sum of a list of numbers.

    Parameters:
    nums (list of float): List of numbers (float or int).

    Returns:
    float: Sum of the numbers.
    """
    return sum(nums)

def average(nums):
    """
    Calculates the average of a list of numbers.

    Parameters:
    nums (list of float): List of numbers (float or int).

    Returns:
    float: Average of the numbers.
    """
    return sum(nums) / len(nums)

def find_max(nums):
    """
    Finds the maximum value in a list of numbers.

    Parameters:
    nums (list of float): List of numbers (float or int).

    Returns:
    float: Maximum number.
    """
    return max(nums)

def find_min(nums):
    """
    Finds the minimum value in a list of numbers.

    Parameters:
    nums (list of float): List of numbers (float or int).

    Returns:
    float: Minimum number.
    """
    return min(nums)

def get_nums():
    """
    Prompts the user to enter a list of numbers.

    Returns:
    list of float: The list of numbers entered by the user.
    """
    while True:
        try:
            numbers = list(map(float, input("Enter numbers separated by spaces: ").split()))
            if not numbers:
                print("Error: The list cannot be empty. Please enter at least one number.")
                continue
            return numbers
        except ValueError:
            print("Error: Invalid input. Please enter numbers separated by spaces.")

def main():
    operations = {
        "1": ("Sum", find_sum),
        "2": ("Average", average),
        "3": ("Maximum", find_max),
        "4": ("Minimum", find_min)
    }

    while True:
        print("\nChoose a mathematical operation:")
        for key, (name, _) in operations.items():
            print(f"{key}. {name}")

        choice = input("Enter the number of the operation you want to perform: ").strip()

        if choice not in operations:
            print("Invalid choice. Please select a valid option.")
            continue

        operation_name, operation_func = operations[choice]
        print(f"You have selected: {operation_name}")

        num = get_nums()
        result = operation_func(num)

        print(f"Result: {result}")

        again = input("Do you want to perform another operation? (yes/no): ").strip().lower()
        if again != "yes":
            print("End of program!")
            break

if __name__ == "__main__":
    main()



Choose a mathematical operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter the number of the operation you want to perform: 1
You have selected: Sum
Enter numbers separated by spaces: 2 5
Result: 7.0
Do you want to perform another operation? (yes/no): no
End of program!


# **Exercies on List Manupilation**

**1. Extract Every Other Element:**

  Write a Python function that extracts every other element from a list, starting from the first element.

  Requirements:
- Define a function extract every other(lst) that takes a list lst as input and returns a
new list containing every other element from the original list.
- Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].


In [7]:
def extract(lst):
  """
  Extracts every other elemet from a list, starting from the first element.

  Parameters:
  lst (list): The input list

  Returns:
  list: a new list containing every other element from the original list
  """
  return lst[::2] #slice operator (start : stop : step)

def main():
    user_input = input("Enter elements separated by space: ").split()
    print(f"List:", user_input)
    print(f"Every other element in the list: {extract(user_input)}")

if __name__ == "__main__":
    main()

Enter elements separated by space: 1 4 6 8 0 2 
List: ['1', '4', '6', '8', '0', '2']
Every other element in the list: ['1', '6', '0']


**2. Slice a Sublist:**

  Write a Python function that returns a sublist from a given list, starting from a specified index and ending at another specified index.

  Requirements:
- Define a function get sublist(lst, start, end) that takes a list lst, a starting index start, and an ending index end as input and returns the sublist from start to end (inclusive).
- Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should be [3, 4, 5].

In [9]:
def get_sublist(lst, start, end):
  """
  Returns a sublist from a given list, starting from a specified index and ending at another specified index.

  Parameters:
  lst (list): The input list
  start (int): The starting index
  end (int): The ending index

  Returns:
  list: The sublist from start to end (inclusive)

  """

  return lst[start:end+1]

lst = [1, 2, 3, 4, 5, 6]
start = 2
end = 4

result = get_sublist(lst, start, end)
print("Original list:", lst)
print("The sublist from the specified start to end is: ", result)

Original list: [1, 2, 3, 4, 5, 6]
The sublist from the specified start to end is:  [3, 4, 5]


**3. Reverse a List Using Slicing:**

  Write a Python function that reverses a list using slicing.

  Requirements:
- Define a function reverse list(lst) that takes a list lst and returns a reversed list using slicing.
- Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].

In [11]:
def reverse(lst):
  return lst[::-1]

lst = [1, 2, 3, 4, 5, 6]
result = reverse(lst)

print("Original list:", lst)
print("The reversed list is: ", result)

Original list: [1, 2, 3, 4, 5, 6]
The reversed list is:  [6, 5, 4, 3, 2, 1]


**4. Remove the First and Last Elements:**

  Write a Python function that removes the first and last elements of a list and returns the resulting sublist.

  Requirements:
- Define a function remove first last(lst) that takes a list lst and returns a sublist without
the first and last elements using slicing.
- Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].

In [12]:
def remove(lst):
  return lst[1:-1]

lst = [1, 2, 3, 4, 5, 6, 7, 8]
result = remove(lst)

print("Original list:", lst)
print("The sublist without the first and last elements is: ", result)

Original list: [1, 2, 3, 4, 5, 6, 7, 8]
The sublist without the first and last elements is:  [2, 3, 4, 5, 6, 7]


**5. Get the First n Elements:**

  Write a Python function that extracts the first n elements from a list.

  Requirements:
- Define a function get first n(lst, n) that takes a list lst and an integer n as input and returns the first n elements of the list using slicing.
- Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].

In [13]:
def get_first_n(lst, n):
  return lst[:n]

lst = [1, 2, 3, 4, 5, 6, 7, 8]
n = 4

result = get_first_n(lst, n)

print("Original list:", lst)
print("The first", n, "elements of the list are: ", result)

Original list: [1, 2, 3, 4, 5, 6, 7, 8]
The first 4 elements of the list are:  [1, 2, 3, 4]


**6. Extract Elements from the End:**

  Write a Python function that extracts the last n elements of a list using slicing.

  Requirements:
- Define a function get last n(lst, n) that takes a list lst and an integer n as input and returns the last n elements of the list.
- Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].

In [14]:
def get_last_n(lst, n):
  return lst[-n:]

lst = [1, 2, 3, 4, 5, 6, 7, 8]
n = 4

result = get_last_n(lst, n)

print("Original list:", lst)
print("The last", n, "elements of the list are: ", result)

Original list: [1, 2, 3, 4, 5, 6, 7, 8]
The last 4 elements of the list are:  [5, 6, 7, 8]


**7. Extract Elements in Reverse Order:**

  Write a Python function that extracts a list of elements in reverse order starting from the second-to-last element and skipping one element in between.

  Requirements:
- Define a function reverse skip(lst) that takes a list lst and returns a new list containing every second element starting from the second-to-last, moving backward.
- Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1].

In [15]:
def reverse_skip(lst):
  return lst[-2::-2]

lst = [1, 2, 3, 4, 5, 6, 7, 8]
result = reverse_skip(lst)

print("Original list:", lst)
print("Every other element in reverse order: ", result)

Original list: [1, 2, 3, 4, 5, 6, 7, 8]
Every other element in reverse order:  [7, 5, 3, 1]


# **Exercises on Nested List**

**1. Flatten a Nested List:**

  Write a Python function that takes a nested list and flattens it into a single list, where all the elements are in a single dimension.

  Requirements:
- Define a function flatten(lst) that takes a nested list lst and returns a flattened version of the list.
- Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].

In [19]:
def flatten(lst):
    flat_list = []
    for item in lst:
        if isinstance(item, list):
            flat_list.extend(flatten(item))
        else:
            flat_list.append(item)
    return flat_list

def main():
    x = int(input("Enter the number of sublists: "))
    list1 = []

    for i in range(x):
        y = int(input(f"Enter the number of elements in sublist {i+1}: "))
        sublist = []
        for j in range(y):
            sublist.append(input(f"Enter element {j+1} of sublist {i+1}: "))
        list1.append(sublist)

    print("Original Nested List:", list1)
    print("Flattened List:", flatten(list1))

if __name__ == "__main__":
    main()


Enter the number of sublists: 3
Enter the number of elements in sublist 1: 3
Enter element 1 of sublist 1: 1
Enter element 2 of sublist 1: 2
Enter element 3 of sublist 1: 3
Enter the number of elements in sublist 2: 4
Enter element 1 of sublist 2: 1
Enter element 2 of sublist 2: 2
Enter element 3 of sublist 2: 4
Enter element 4 of sublist 2: 7
Enter the number of elements in sublist 3: 3
Enter element 1 of sublist 3: 4
Enter element 2 of sublist 3: 3
Enter element 3 of sublist 3: 6
Original Nested List: [['1', '2', '3'], ['1', '2', '4', '7'], ['4', '3', '6']]
Flattened List: ['1', '2', '3', '1', '2', '4', '7', '4', '3', '6']


**2. Accessing Nested List Elements:**

  Write a Python function that extracts a specific element from a nested list given its indices.

  Requirements:
- Define a function access nested element(lst, indices) that takes a nested list lst and a list of indices indices, and returns the element at that position.
- Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1, 2], the output should be 6.

In [24]:
def access_nested_element(lst, indices):
    elem = lst
    for index in indices:
        elem = elem[index]
    return elem

def main():
    x = int(input("Enter the number of sublists: "))
    list1 = []

    for i in range(x):
        y = int(input(f"Enter the number of elements in sublist {i+1}: "))
        sublist = []
        for j in range(y):
            sublist.append(input(f"Enter element {j+1} of sublist {i+1}: "))
        list1.append(sublist)

    print("Original Nested List:", list1)

    indices = list(map(int, input("Enter indices separated by space: ").split()))

    try:
        print("Element at indices", indices, ":", access_nested_element(list1, indices))
    except IndexError:
        print("Error: Indices out of range!")

if __name__ == "__main__":
    main()

Enter the number of sublists: 4
Enter the number of elements in sublist 1: 1
Enter element 1 of sublist 1: 2
Enter the number of elements in sublist 2: 3
Enter element 1 of sublist 2: 3
Enter element 2 of sublist 2: 4
Enter element 3 of sublist 2: 5
Enter the number of elements in sublist 3: 4
Enter element 1 of sublist 3: 2
Enter element 2 of sublist 3: 5
Enter element 3 of sublist 3: 7
Enter element 4 of sublist 3: 4
Enter the number of elements in sublist 4: 3
Enter element 1 of sublist 4: 2
Enter element 2 of sublist 4: 4
Enter element 3 of sublist 4: 1
Original Nested List: [['2'], ['3', '4', '5'], ['2', '5', '7', '4'], ['2', '4', '1']]
Enter indices separated by space: 2 3
Element at indices [2, 3] : 4


**3. Sum of All Elements in a Nested List:**

  Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).

  Requirements:
- Define a function sum nested(lst) that takes a nested list lst and returns the sum of all the elements.
- Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21.

In [25]:
def sum_nested(lst):
    return sum(flatten(lst))

def main():
    x = int(input("Enter the number of sublists: "))
    list1 = []

    for i in range(x):
        y = int(input(f"Enter the number of elements in sublist {i+1}: "))
        sublist = []
        for j in range(y):
            sublist.append(int(input(f"Enter element {j+1} of sublist {i+1}: ")))
        list1.append(sublist)

    print("Original Nested List:", list1)
    print("Sum of all elements:", sum_nested(list1))

if __name__ == "__main__":
    main()


Enter the number of sublists: 3
Enter the number of elements in sublist 1: 2
Enter element 1 of sublist 1: 4
Enter element 2 of sublist 1: 5
Enter the number of elements in sublist 2: 2
Enter element 1 of sublist 2: 4
Enter element 2 of sublist 2: 5
Enter the number of elements in sublist 3: 7
Enter element 1 of sublist 3: 8
Enter element 2 of sublist 3: 3
Enter element 3 of sublist 3: 2
Enter element 4 of sublist 3: 4
Enter element 5 of sublist 3: 3
Enter element 6 of sublist 3: 2
Enter element 7 of sublist 3: 1
Original Nested List: [[4, 5], [4, 5], [8, 3, 2, 4, 3, 2, 1]]
Sum of all elements: 41


**4. Remove Specific Element from a Nested List:**
  
  Write a Python function that removes all occurrences of a specific element from a nested list.

  Requirements:
- Define a function remove element(lst, elem) that removes elem from lst and returns the modified list.
- Example: For the input lst = [[1, 2], [3, 2], [4, 5]] and elem = 2, the output should be [[1], [3], [4, 5]].

In [29]:
def remove_element(lst, elem):
    if isinstance(lst, list):
        return [remove_element(sublist, elem) for sublist in lst if sublist != elem]
    return lst if lst != elem else None

def clean_list(lst):
    if isinstance(lst, list):
        return [clean_list(item) for item in lst if item is not None]
    return lst

def main():
    x = int(input("Enter the number of sublists: "))
    list1 = []

    for i in range(x):
        y = int(input(f"Enter the number of elements in sublist {i+1}: "))
        sublist = []
        for j in range(y):
            sublist.append(int(input(f"Enter element {j+1} of sublist {i+1}: ")))
        list1.append(sublist)

    elem = int(input("Enter element to remove: "))
    modified_list = clean_list(remove_element(list1, elem))

    print("Original Nested List:", list1)
    print("Modified list:", modified_list)

if __name__ == "__main__":
    main()

Enter the number of sublists: 3
Enter the number of elements in sublist 1: 2
Enter element 1 of sublist 1: 4
Enter element 2 of sublist 1: 5
Enter the number of elements in sublist 2: 3
Enter element 1 of sublist 2: 1
Enter element 2 of sublist 2: 4
Enter element 3 of sublist 2: 5
Enter the number of elements in sublist 3: 3
Enter element 1 of sublist 3: 6
Enter element 2 of sublist 3: 5
Enter element 3 of sublist 3: 4
Enter element to remove: 4
Original Nested List: [[4, 5], [1, 4, 5], [6, 5, 4]]
Modified list: [[5], [1, 5], [6, 5]]


**5. Find the Maximum Element in a Nested List:**

  Write a Python function that finds the maximum element in a nested list (regardless of depth).

  Requirements:
- Define a function find max(lst) that takes a nested list lst and returns the maximum element.
- Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.

In [ ]:
def find_max(lst):
  max_val = float('-inf')
  for item in lst:
    if isinstance(item, list):
      max_val = max(max_val, find_max(item))
    else:
      max_val = max(max_val, item)
  return max_val
lst = [[1, 2, 3], [4, 5,[10,11], 6], [7, 8, 9]]
print("Original list:", lst)
max_value = find_max(lst)
print("The maximum element in the nested list is:",max_value)


Original list: [[1, 2, 3], [4, 5, [10, 11], 6], [7, 8, 9]]
The maximum element in the nested list is: 11


**6. Count Occurrences of an Element in a Nested List:**

  Write a Python function that counts how many times a specific element appears in a nested list.

  Requirements:
- Define a function count occurrences(lst, elem) that counts the occurrences of elem in the nested list lst.
- Example: For the input lst = [[1, 2], [2, 3], [2, 4]] and elem = 2, the output should be 3.

In [ ]:
def count_occurrences(lst, elem):
  count = 0
  for item in lst:
    if isinstance(item,list):
      count += count_occurrences(item, elem)
    elif item == elem:
      count += 1
  return count

lst = [[1, 7, 3], [4, 5,[10,7], 6], [7, 7, 9]]
print("Original list:", lst)
elem = 7
res = count_occurrences(lst,elem)
print(f"Number of occurrences of {elem} in the nested list is: ", res)

Original list: [[1, 7, 3], [4, 5, [10, 7], 6], [7, 7, 9]]
Number of occurrences of 7 in the nested list is:  4


**7. Flatten a List of Lists of Lists:**

  Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.

  Requirements:
- Define a function deep flatten(lst) that takes a deeply nested list lst and returns a single flattened list.
- Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be [1, 2, 3, 4, 5, 6, 7, 8].

In [ ]:
def deep_flatten(lst):
  flattened_lst = []
  for item in lst:
    if isinstance(item, list):
      flattened_lst.extend(deep_flatten(item))
    else:
      flattened_lst.append(item)
  return flattened_lst

lst = [[1, 7, 3], [4, 5,[10,17], 6], [7, 71, 9]]
print("Original list:", lst)
flattened_lst = deep_flatten(lst)
print("Flattened list:", flattened_lst)

Original list: [[1, 7, 3], [4, 5, [10, 17], 6], [7, 71, 9]]
Flattened list: [1, 7, 3, 4, 5, 10, 17, 6, 7, 71, 9]


**8. Nested List Average:**

  Write a Python function that calculates the average of all elements in a nested list.

  Requirements:
- Define a function average nested(lst) that takes a nested list lst and returns the average of all the elements.
- Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5.

In [ ]:
def avg_nested(lst):
  flattened_lst = deep_flatten(lst)
  total = sum(flattened_lst)
  return total/len(flattened_lst)
lst = [[1, 2, 3], [4, 5,[10,11], 6], [7, 8, 9]]
print("Original list:", lst)
res = avg_nested(lst)
print("The average of all the elements in the nested list is: ", res)

Original list: [[1, 2, 3], [4, 5, [10, 11], 6], [7, 8, 9]]
The average of all the elements in the nested list is:  6.0


# **Basic Vector and Matrix Operations with Numpy**

**Problem - 1: Array Creation : **

Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [34]:
import numpy as np

# 1. Initialize an empty array with size 2x2
empty_array = np.empty((2, 2))
print("1. Empty Array (2x2):\n", empty_array)

# 2. Initialize an all-one array with size 4x2
ones_array = np.ones((4, 2))
print("\n2. All Ones Array (4x2):\n", ones_array)

# 3. Return a new array of given shape and type, filled with a fill value
fill_value_array = np.full((3, 3), 7)
print("\n3. Array filled with 7 (3x3):\n", fill_value_array)

# 4. Return a new array of zeros with the same shape and type as a given array
reference_array = np.array([[1, 2], [3, 4]])
zeros_like_array = np.zeros_like(reference_array)
print("\n4. Zeros Array with Same Shape as Reference Array:\n", zeros_like_array)

# 5. Return a new array of ones with the same shape and type as a given array
ones_like_array = np.ones_like(reference_array)
print("\n5. Ones Array with Same Shape as Reference Array:\n", ones_like_array)

# 6. Convert an existing list to a NumPy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\n6. Converted NumPy Array:\n", numpy_array)


1. Empty Array (2x2):
 [[2.63540747e-316 0.00000000e+000]
 [4.94065646e-324             nan]]

2. All Ones Array (4x2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Array filled with 7 (3x3):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

4. Zeros Array with Same Shape as Reference Array:
 [[0 0]
 [0 0]]

5. Ones Array with Same Shape as Reference Array:
 [[1 1]
 [1 1]]

6. Converted NumPy Array:
 [1 2 3 4]


**Problem - 2: Array Manipulation : Numerical Ranges and Array Indexing**

**1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.**

In [35]:
print("Array with values ranging from 10 to 49: \n",np.arange(10,50))

Array with values ranging from 10 to 49: 
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


**2. Create a 3X3 matrix with values ranging from 0 to 8. {Hint:look for np.reshape()}**

In [36]:
array = np.arange(9)
matrix = np.reshape(array,(3,3))
print("3X3 matrix with values ranging from 0 to 8: \n",matrix)

3X3 matrix with values ranging from 0 to 8: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


**3. Create a 3X3 identity matrix.{Hint:np.eye()}**

In [37]:
print("3X3 identity matrix: \n", np.eye(3,dtype=int))

3X3 identity matrix: 
 [[1 0 0]
 [0 1 0]
 [0 0 1]]


**4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}**

In [38]:
random_arr = np.random.random(30)
print(f"Random array of size 30:\n{random_arr}")
mean = np.mean(random_arr)
print("\nMean:",mean)

Random array of size 30:
[0.37085992 0.3439194  0.82697765 0.16215215 0.83737666 0.52319697
 0.94133099 0.6282488  0.05888543 0.64622981 0.51973014 0.99259489
 0.442438   0.31521111 0.47907597 0.51118531 0.29222121 0.0366069
 0.07304829 0.5758699  0.65312976 0.75805893 0.4859633  0.36043308
 0.77479617 0.11284028 0.49710221 0.48142196 0.79225347 0.31494744]

Mean: 0.4936035352784609


**5. Create a 10X10 array with random values and find the minimum and maximum values.**

In [39]:
array = np.random.random((10, 10))
print(f"10X10 array with random values:\n{array}")
print(f"\nMinimum value: {np.min(array)}")
print(f"\nMaximum value: {np.max(array)}")

10X10 array with random values:
[[0.26329465 0.10714817 0.33331662 0.96241004 0.71048553 0.62228657
  0.26273994 0.51645123 0.12855248 0.00310997]
 [0.80743052 0.5452145  0.5945465  0.34338553 0.66264321 0.46222918
  0.55695428 0.818035   0.20326886 0.03030756]
 [0.37980597 0.99130119 0.86295861 0.80481271 0.82395037 0.59584946
  0.89028788 0.87985391 0.74035526 0.68265093]
 [0.33164022 0.80823332 0.99649169 0.2079161  0.33190296 0.16894273
  0.99704925 0.45088452 0.73431241 0.81678327]
 [0.76780782 0.93473061 0.95764892 0.36757576 0.45594318 0.80399433
  0.77642552 0.6849168  0.73028989 0.58193441]
 [0.16301299 0.64057371 0.73386011 0.89372862 0.37333315 0.9464977
  0.68836465 0.33034092 0.28585946 0.12499831]
 [0.15407474 0.80536047 0.23420203 0.24862539 0.73841755 0.64672901
  0.99227119 0.45983411 0.28235623 0.8216678 ]
 [0.32323894 0.56971114 0.77361227 0.85725679 0.50824327 0.44859725
  0.31359755 0.67391808 0.40473324 0.24677765]
 [0.53512478 0.38469144 0.97966042 0.10797398 0.2

**6. Create a zero array of size 10 and replace 5th element with 1.**

In [40]:
zero_arr = np.zeros(10, dtype=int)
zero_arr[4] = 1
print("Array:",zero_arr)

Array: [0 0 0 0 1 0 0 0 0 0]


**7. Reverse an array arr = [1,2,0,0,4,0].**

In [41]:
arr = [1,2,0,0,4,0]
reversed_arr = arr[::-1]
print("Original array:",arr)
print("Reversed array:",reversed_arr)

Original array: [1, 2, 0, 0, 4, 0]
Reversed array: [0, 4, 0, 0, 2, 1]


**8. Create a 2d array with 1 on border and 0 inside.**

In [42]:
arr = np.ones((5,5), dtype=int)
arr[1:-1,1:-1] = 0
print("2d array with 1 on border and 0 inside:\n",arr)

2d array with 1 on border and 0 inside:
 [[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


**9. Create a 8X8 matrix and fill it with a checkerboard pattern.**

In [43]:
arr = np.zeros((8,8), dtype=int)
arr[1::2,::2] = 1
arr[::2,1::2] = 1
print("Checkerboard pattern:\n",arr)

Checkerboard pattern:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


**Problem - 3: Array Operations:**

For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [44]:
import numpy as np

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays
add_xy = x + y
print("Addition of x and y:\n", add_xy)

# 2. Subtract the two arrays
sub_xy = x - y
print("\nSubtraction of x and y:\n", sub_xy)

# 3. Multiply the array x with any integer (e.g., 3)
mult_x = x * 3
print("\nMultiplication of x with 3:\n", mult_x)

# 4. Find the square of each element of x
square_x = x ** 2
print("\nSquare of each element of x:\n", square_x)

# 5. Dot product calculations
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)

print("\nDot product of v and w:", dot_vw)
print("\nDot product of x and v:\n", dot_xv)
print("\nDot product of x and y:\n", dot_xy)

# 6. Concatenation
concat_xy_row = np.concatenate((x, y), axis=0)  # Along rows
concat_vw_col = np.vstack((v, w))  # Along columns

print("\nConcatenation of x and y along rows:\n", concat_xy_row)
print("\nConcatenation of v and w along columns:\n", concat_vw_col)

# 7. Concatenate x and v
try:
    concat_xv = np.concatenate((x, v), axis=0)  # Attempting to concatenate x and v
    print("\nConcatenation of x and v:\n", concat_xv)
except ValueError as e:
    print("\nError while concatenating x and v:", e)
    print("Reason: x has shape (2,2) and v has shape (2,). Their dimensions are incompatible for direct concatenation.")


Addition of x and y:
 [[ 6  8]
 [10 13]]

Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]

Multiplication of x with 3:
 [[ 3  6]
 [ 9 15]]

Square of each element of x:
 [[ 1  4]
 [ 9 25]]

Dot product of v and w: 219

Dot product of x and v:
 [29 77]

Dot product of x and y:
 [[19 22]
 [50 58]]

Concatenation of x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenation of v and w along columns:
 [[ 9 10]
 [11 12]]

Error while concatenating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Reason: x has shape (2,2) and v has shape (2,). Their dimensions are incompatible for direct concatenation.


**Problem 4 : Matrix Operations :**
- For the following arrays:

  A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);

  Prove following with Numpy:
  1. Prove A.A−1 = I.
  2. Prove AB ̸= BA.
  3. Prove(AB)T =BTAT.

In [47]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

In [48]:
from numpy import linalg

inverse_A = np.linalg.inv(A)
result_1 = np.dot(A, inverse_A)
print(f"1. A.A−1:\n{np.round(result_1)}")

dot_product_AB = np.dot(A, B)
dot_product_BA = np.dot(B, A)

check = np.array_equal(dot_product_AB, dot_product_BA)
print("\n")
if check == True:
  print("2. AB = BA")
else:
  print("2. AB != BA")

transpose_A = np.transpose(A)
transpose_B = np.transpose(B)

product_BTAT = np.dot(transpose_B, transpose_A)
transpose_AB = np.transpose(dot_product_AB)

check1 = np.array_equal(transpose_AB, product_BTAT)
print("\n")
if check1 == True:
  print("3. (AB)T = BT.AT")
else:
  print("3. (AB)T != BT.AT")

1. A.A−1:
[[1. 0.]
 [0. 1.]]


2. AB != BA


3. (AB)T = BT.AT


**Solve the following system of Linear equation using Inverse Methods.**

  2x − 3y + z = −1

  x − y + 2z = −3

  3x + y − z = 9

  {Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

In [ ]:
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

B = np.array([-1, -3, 9])

In [ ]:
print("Coefficient matrix A:")
print(A)
print("\nConstant matrix B:")
print(B)

Coefficient matrix A:
[[ 2 -3  1]
 [ 1 -1  2]
 [ 3  1 -1]]

Constant matrix B:
[-1 -3  9]


In [ ]:
det_A = np.linalg.det(A)

cofactor_matrix = np.zeros_like(A, dtype=float)

for i in range(A.shape[0]):
    for j in range(A.shape[1]):
        minor_matrix = np.delete(np.delete(A, i, axis=0), j, axis=1)
        cofactor_matrix[i, j] = ((-1) ** (i + j)) * np.linalg.det(minor_matrix)

adjugate_matrix = cofactor_matrix.T

# inverse of A
A_inv = adjugate_matrix / det_A

In [ ]:
X = np.dot(A_inv, B)
print("Solution using Inverse Methods:")
print(X)

Solution using Inverse Methods:
[ 2.  1. -2.]


**Solve the above equation using np.linalg.inv function. {Explore more about ”linalg” func- tion of Numpy}**

In [ ]:
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
print("Solution using np.linalg.inv function:")
print(X)

Solution using np.linalg.inv function:
[ 2.  1. -2.]


**Experiment: How Fast is Numpy?**

**1. Element-wise Addition:**

  Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.
  Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.

In [ ]:
import time

lst1 = [i for i in range(1,1000001)]
lst2 = [i for i in range(1000001,2000001)]

start_time = time.time()
result_time = [a+b for a,b in zip(lst1, lst2)]
end_time = time.time()
add_time = end_time - start_time
print(f"Time taken for element-wise addition: {add_time} seconds")

arr1 = np.array(lst1)
arr2 = np.array(lst2)

start_time = time.time()
result_array = arr1 + arr2
end_time = time.time()
array_time = end_time - start_time
print(f"Time taken for element-wise addition using Numpy arrays: {array_time} seconds")

Time taken for element-wise addition: 0.157271146774292 seconds
Time taken for element-wise addition using Numpy arrays: 0.004817485809326172 seconds


**2. Element-wise Multiplication**

- Using Python Lists, perform element-wise multiplication of two lists of size 1,000,000. Measure and Print the time taken for this operation.
- Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.

In [ ]:
start_time = time.time()
result_lst = [a*b for a,b in zip(lst1, lst2)]
end_time = time.time()
multiplication_time = end_time - start_time
print(f"Time taken for element-wise multiplication: {multiplication_time} seconds")

array1 = np.array(lst1)
array2 = np.array(lst2)

start_time = time.time()
result_array = array1 * array2
end_time = time.time()
array_time = end_time - start_time
print(f"Time taken for element-wise multiplication using Numpy arrays: {array_time} seconds")

Time taken for element-wise multiplication: 0.5114076137542725 seconds
Time taken for element-wise multiplication using Numpy arrays: 0.00566554069519043 seconds


**3. Dot Product**

- Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.
- Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.

In [ ]:
start_time = time.time()
result_time = [a*b for a,b in zip(lst1, lst2)]
end_time = time.time()
dot_product_time = end_time - start_time
print(f"Time taken to compute the dot product: {dot_product_time} seconds")

array1 = np.array(lst1)
array2 = np.array(lst2)

start_time = time.time()
dot_product_array = np.dot(array1, array2)
end_time = time.time()
array_time = end_time - start_time
print(f"Time taken to compute the dot product using Numpy arrays: {array_time} seconds")

Time taken to compute the dot product: 0.09782075881958008 seconds
Time taken to compute the dot product using Numpy arrays: 0.002732992172241211 seconds


**4. Matrix Multiplication**

- Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.
- Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.

In [ ]:
N=1000

matrix1 = [[i + j for j in range(N)] for i in range(N)]
matrix2 = [[i - j for j in range(N)] for i in range(N)]

def mat_mul(A,B):
  result = [[0] *N for _ in range(N)]
  for i in range(N):
    for j in range(N):
      for k in range(N):
        result[i][j] += A[i][k] * B[k][j]
  return result

start_time = time.time()
result = mat_mul(matrix1, matrix2)
end_time = time.time()
mat_mul_time = end_time - start_time
print(f"Time taken for matrix multiplication: {mat_mul_time} seconds")

array1 = np.array(matrix1)
array2 = np.array(matrix2)

start_time = time.time()
result_numpy = np.dot(array1, array2)
end_time = time.time()
numpy_matmul_time = end_time - start_time
print(f"Time taken for matrix multiplication using Numpy arrays: {numpy_matmul_time:.6f} seconds")

Time taken for matrix multiplication: 184.4673342704773 seconds
Time taken for matrix multiplication using Numpy arrays: 2.215079 seconds
